name: data_repository
description: A data repository for flutter, manages both local and remote api access
version: 0.5.0
homepage: https://github.com/wiseminds/data-repository
repository: https://github.com/wiseminds/data-repository

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  mockito: ^5.4.6
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15
