name: Flutter-CI
on:
  push:
    branches: [main, web]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 
      - uses: subosito/flutter-action@v1
        with:
          channel: stable


      # - name: Go to example folder
      #   run: cd example             

      - name: Install dependencies
        run: cd example && flutter build web

      - name: Analyze project source
        run: flutter analyze

      # - name: Run tests
      #   run: dart test   

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build/web 
  